# Generated by Django 5.0.7 on 2026-08-07 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial'),
        ('users', '0002_remove_tenantprofile_user_landlord_tenant_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='houseunit',
            options={'ordering': ['property', 'unit_number'], 'verbose_name': 'House Unit'},
        ),
        migrations.AddField(
            model_name='houseunit',
            name='unit_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.CharField(blank=True, db_column='location', max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('INACTIVE', 'Inactive')], default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='houseunit',
            name='id',
            field=models.BigAutoField(db_column='unit_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='houseunit',
            name='property',
            field=models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.BigAutoField(db_column='property_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='landlord',
            field=models.ForeignKey(db_column='landlord_id', on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='users.landlord'),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(db_column='property_name', max_length=200),
        ),
    ]
