# Generated by Django 5.0.7 on 2026-09-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_houseunit_options_houseunit_unit_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('APARTMENT', 'Apartment'), ('HOUSE', 'House'), ('ROOM', 'Room')], max_length=20),
        ),
    ]
