# Generated by Django 5.0.7 on 2026-08-07 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_houseunit_options_houseunit_unit_type_and_more'),
        ('rentals', '0002_initial'),
        ('users', '0002_remove_tenantprofile_user_landlord_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalagreement',
            name='house_unit',
            field=models.ForeignKey(db_column='unit_id', on_delete=django.db.models.deletion.CASCADE, related_name='rental_agreements', to='properties.houseunit'),
        ),
        migrations.AlterField(
            model_name='rentalagreement',
            name='id',
            field=models.BigAutoField(db_column='agreement_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rentalagreement',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='rental_agreements', to='users.tenant'),
        ),
    ]
