# Generated by Django 5.0.7 on 2026-07-08 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='rental_agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='rentals.rentalagreement'),
        ),
        migrations.AddField(
            model_name='paymentgatewaylog',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gateway_logs', to='payments.payment'),
        ),
    ]
