# Generated by Django 5.0.7 on 2026-08-07 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
        ('rentals', '0003_alter_rentalagreement_house_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.BigAutoField(db_column='payment_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('MOBILE_MONEY', 'Mobile Money'), ('CLICKPESA', 'ClickPesa Mobile Money')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='rental_agreement',
            field=models.ForeignKey(db_column='agreement_id', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='rentals.rentalagreement'),
        ),
        migrations.AlterField(
            model_name='paymentgatewaylog',
            name='payment',
            field=models.ForeignKey(blank=True, db_column='payment_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gateway_logs', to='payments.payment'),
        ),
    ]
