# Generated by Django 5.0.7 on 2026-08-07 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_tenantprofile_user_landlord_tenant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='employer_name',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='employment_status',
        ),
    ]
