# Generated by Django 5.0.7 on 2026-08-07 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_tenant_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlord',
            name='business_registration_number',
        ),
        migrations.RemoveField(
            model_name='landlord',
            name='verification_documents',
        ),
    ]
