# Generated by Django 5.0.7 on 2026-09-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_gender_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlord',
            name='address',
        ),
        migrations.RemoveField(
            model_name='landlord',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='landlord',
            name='email',
        ),
        migrations.RemoveField(
            model_name='landlord',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='landlord',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='landlord',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='landlord',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='address',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('LOCAL', 'Local'), ('GOOGLE', 'Google')], db_column='auth_provider', default='LOCAL', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='google_access_token',
            field=models.TextField(blank=True, db_column='google_access_token', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, db_column='google_id', max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
