# Generated by Django 5.0.7 on 2026-09-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_landlord_address_remove_landlord_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, db_column='google_id', max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='google_access_token',
            field=models.TextField(blank=True, db_column='google_access_token', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('LOCAL', 'Local'), ('GOOGLE', 'Google')], db_column='auth_provider', default='LOCAL', max_length=20),
        ),
    ]
